# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AcDeck < Formula
  desc "Unofficial CLI for AtCoder users"
  homepage "https://github.com/sachaos/ac-deck"
  version "0.7.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/sachaos/ac-deck/releases/download/v0.7.0/ac-deck_0.7.0_Darwin_x86_64.tar.gz"
    sha256 "7d68285fd9579db65713b35eaaebcf4e1fdd2a927b8d8b11c94d23957998c6d6"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/sachaos/ac-deck/releases/download/v0.7.0/ac-deck_0.7.0_Linux_x86_64.tar.gz"
    sha256 "51a5a382a50e4c1ad758d85015fa823c5c08899488c161ad00f5252ca8ced116"
  end

  def install
    bin.install "acd"
  end

  test do
    system "#{bin}/acd", "--version"
  end
end
