# This file was generated by GoReleaser. DO NOT EDIT.
class Atcoder < Formula
  desc "Unofficial CLI for AtCoder users"
  homepage "https://github.com/sachaos/atcoder"
  version "0.2.10"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/sachaos/atcoder/releases/download/v0.2.10/atcoder_0.2.10_Darwin_x86_64.tar.gz"
    sha256 "7f0bbeef9da222c8ca95bd600141f6a8576606be8db0d317368e518eae25e91c"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/sachaos/atcoder/releases/download/v0.2.10/atcoder_0.2.10_Linux_x86_64.tar.gz"
      sha256 "28eed68599952bd869a686ec7bb6c4dd63174cdc1d9f762c8517e37247c2dab1"
    end
  end

  def install
    bin.install "atcoder"
  end

  test do
    system "#{bin}/atcoder", "--version"
  end
end
