# This file was generated by GoReleaser. DO NOT EDIT.
class GoStarz < Formula
  desc "Show GitHub stars"
  homepage "https://github.com/sachaos/go-starz"
  version "0.0.2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/sachaos/go-starz/releases/download/v0.0.2/go-starz_0.0.2_Darwin_x86_64.tar.gz"
    sha256 "035de7835b72091e11e73924c8fa8489a7fb752ff14510657cf68fb1591c389e"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/sachaos/go-starz/releases/download/v0.0.2/go-starz_0.0.2_Linux_x86_64.tar.gz"
      sha256 "6e0f304138c22b74932a60df3656908c88a0d204382ae38cbf07a2fe82c21b18"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
      else
        url "https://github.com/sachaos/go-starz/releases/download/v0.0.2/go-starz_0.0.2_Linux_armv6.tar.gz"
        sha256 "bba76e668de32c9cd92a43c98c803174bf069428d7a515aa7e4db46d25d58d57"
      end
    end
  end

  def install
    bin.install "go-starz"
  end

  test do
    system "#{bin}/go-starz", "--version"
  end
end
