# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoStarz < Formula
  desc "Show GitHub stars"
  homepage "https://github.com/sachaos/go-starz"
  version "0.0.3"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sachaos/go-starz/releases/download/v0.0.3/go-starz_0.0.3_darwin_amd64.tar.gz"
      sha256 "ace81ac2478833ec8e5a1b10cfb6ce599b1851b5ece867c46bc5a532474b5f9f"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/sachaos/go-starz/releases/download/v0.0.3/go-starz_0.0.3_linux_amd64.tar.gz"
      sha256 "ed2a5a0ae95a32117ed124c329e8aa68d15afc0c0e77493ebf6624e590ff7da7"
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/sachaos/go-starz/releases/download/v0.0.3/go-starz_0.0.3_linux_armv6.tar.gz"
      sha256 "55d3a24a6259fa55afb3aa9c5841b4818baebe446bb57a962bc9e51a4e94741f"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sachaos/go-starz/releases/download/v0.0.3/go-starz_0.0.3_linux_arm64.tar.gz"
      sha256 "bd7c0285ab582d95c42044aaff2a7b00431ee0f7ea8197db3faf88af3e255a24"
    end
  end

  def install
    bin.install "go-starz"
  end

  test do
    system "#{bin}/go-starz", "--version"
  end
end
