# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Toggl < Formula
  desc "Toggl CLI client"
  homepage "https://github.com/sachaos/toggl"
  version "0.5.0"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sachaos/toggl/releases/download/v0.5.0/toggl_0.5.0_Darwin_x86_64.tar.gz"
      sha256 "e0b364da77ca0b6a47d90f37921eb33107f97da596d41626b597ba0918e2d23e"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/sachaos/toggl/releases/download/v0.5.0/toggl_0.5.0_Linux_x86_64.tar.gz"
      sha256 "f0f0bc3a2f40d718e75a9dd6a6d14c762f92dc51f019b4950ef2b27a75718485"
    end
  end

  def install
    bin.install "toggl"
  end

  test do
    system "#{bin}/toggl", "--version"
  end
end
