# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ViddyRc < Formula
  desc "Modern watch command. Viddy well, gopher. Viddy well."
  homepage "https://github.com/sachaos/viddy"
  version "1.0.0-rc.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/sachaos/viddy/releases/download/v1.0.0-rc.1/viddy-v1.0.0-rc.1-macos-arm64.tar.gz"
      sha256 "3fb43565aa18b3f0a321f1d582c22b434d61d17dd022a5ed1e9c7ea33e8a086d"

      def install
        bin.install "viddy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sachaos/viddy/releases/download/v1.0.0-rc.1/viddy-v1.0.0-rc.1-macos-x86_64.tar.gz"
      sha256 "ba204aa4f00ef0a85e857acff83081892656cbcf84d6a241ad46590e9061011f"

      def install
        bin.install "viddy"
      end
    end
  end

  test do
    system "#{bin}/viddy", "--version"
  end
end
