# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Viddy < Formula
  desc "Modern waach command. Viddy well, gopher. Viddy well."
  homepage "https://github.com/sachaos/viddy"
  version "0.1.6"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sachaos/viddy/releases/download/v0.1.6/viddy_0.1.6_Darwin_x86_64.tar.gz"
      sha256 "51436be161c06fe17d0034b431fd53a24a8df680ee6b517946055e61a887685b"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/sachaos/viddy/releases/download/v0.1.6/viddy_0.1.6_Linux_x86_64.tar.gz"
      sha256 "62e48d3c49db304b1d9e33d363b5c34696db58374a591d10c5a93b946c7c2ee1"
    end
  end

  def install
    bin.install "viddy"
  end

  test do
    system "#{bin}/viddy", "--version"
  end
end
