# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Viddy < Formula
  desc "Modern watch command. Viddy well, gopher. Viddy well."
  homepage "https://github.com/sachaos/viddy"
  version "0.1.0"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sachaos/viddy/releases/download/v0.1.0/viddy_0.1.0_Darwin_x86_64.tar.gz"
      sha256 "b9a04ab34edfeb2020aa1098d9297baf7132ea54b2dfaeff48bcdac48cdfea62"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/sachaos/viddy/releases/download/v0.1.0/viddy_0.1.0_Linux_x86_64.tar.gz"
      sha256 "40c57f86de56bec271c8fc12dd8dccf6179633d8b647dfb63b866de2944f8103"
    end
  end

  def install
    bin.install "viddy"
  end

  test do
    system "#{bin}/viddy, "--version"
  end
end
