# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ViddyRc < Formula
  desc "Modern watch command. Viddy well, gopher. Viddy well."
  homepage "https://github.com/sachaos/viddy"
  version "1.0.0-rc.5"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/sachaos/viddy/releases/download/v1.0.0-rc.5/viddy-v1.0.0-rc.5-macos-arm64.tar.gz"
      sha256 "41e0e8a8d1d07c198022ff00105d752cd5552352d1f0328362f278ce0f282096"

      def install
        bin.install "viddy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sachaos/viddy/releases/download/v1.0.0-rc.5/viddy-v1.0.0-rc.5-macos-x86_64.tar.gz"
      sha256 "e606b4ea67347afab17f391e55af0d73ba8593fb5c4d66f3dc98f27541f099cc"

      def install
        bin.install "viddy"
      end
    end
  end

  test do
    system "#{bin}/viddy", "--version"
  end
end
