# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Viddy < Formula
  desc "Modern waach command. Viddy well, gopher. Viddy well."
  homepage "https://github.com/sachaos/viddy"
  version "0.1.4"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sachaos/viddy/releases/download/v0.1.4/viddy_0.1.4_Darwin_x86_64.tar.gz"
      sha256 "6c6056788a22a45467b22d71b6bf81eab00ee01500050db67cc65161867043ff"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/sachaos/viddy/releases/download/v0.1.4/viddy_0.1.4_Linux_x86_64.tar.gz"
      sha256 "123b0995600740502557d4ae7b787b31132d5d6e1f175ea55748c6d1a8eaef63"
    end
  end

  def install
    bin.install "viddy"
  end

  test do
    system "#{bin}/viddy", "--version"
  end
end
